---
title: "index"
author: "me"
date: "2025-01-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
install.packages("FNN")
install.packages("corrplot")
install.packages("tree")
install.packages("caret")
install.packages("ggplot2")

library(tidyverse)
library(FNN)
library(corrplot)
library(tree)
library(caret)
library(ggplot2)
options(warn=1)
```

```{r}
Vgsales <- read.csv("./archive/Video_Games_Sales_as_at_22_Dec_2016.csv", sep=",", na.strings = c(""," ","NA", "N/A"), stringsAsFactors = TRUE)
head(Vgsales)

str(Vgsales)

na_count <-  sapply(Vgsales, function(y) sum(is.na(y)))
na_count <-  data.frame(na_count)
na_count
```

```{r}
#  drop all NA values
Vgsales <- na.omit(Vgsales)
str(Vgsales)
```

```{r}
#  drop all sales except global
Vgsales_df <- cbind(Vgsales[,-c(6:10)], Vgsales$Global_Sales)
Vgsales_df$Year_of_Release <-  2016 - Vgsales_df$Year_of_Release
names(Vgsales_df)[3] <- "Game_Age"
names(Vgsales_df)[12] <- "Global_Sales"
str(Vgsales_df)
```

```{r}
summary(Vgsales_df)
```

### Visualizations of the data analysis

## Univariate plots
```{r}
fig <- function(width, height){
  options(repr.plot.width = width, repr.plot.height = height)
}
```


```{r}
fig(20,8)
Platform_bar <- ggplot(Vgsales_df, aes(x=Platform, fill=Platform)) + geom_bar()
Platform_bar
```

```{r}
fig(15,8)
Age_bar <- ggplot(Vgsales_df, aes(x=Game_Age)) + geom_bar(fill="forestgreen")
Age_bar
```


```{r}
fig(50,8)
Genre_bar <- ggplot(Vgsales_df, aes(x=Genre, fill = Genre)) + geom_bar() + theme(axis.text.x=element_text(angle=90, vjust=.5, hjust=1))
Genre_bar
```

```{r}
fig(30,8)
Critic_Score_hist <- ggplot(Vgsales_df, aes(Critic_Score)) + geom_histogram(binwidth=4,color="black", fill="blue")
Critic_Score_hist
```

```{r}
Critic_Count_hist <- ggplot(Vgsales_df, aes(Critic_Count)) + geom_histogram(binwidth = 4, color="black", fill="skyblue")
Critic_Count_hist
```

```{r}
fig(30,8)
Vgsales_df %>% select(Name, User_Score) %>% arrange(desc(User_Score)) %>% head(10) %>% 
  ggplot(aes(x=Name, y=User_Score, fill = Name)) + geom_bar(stat="identity") + theme(axis.text.x =element_text(angle=90, vjust=.5,hjust=1))
```

```{r}
fig(20, 8)
User_Count_hist <- ggplot(Vgsales_df, aes(User_Count)) + geom_histogram(color="black", fill="skyblue")
User_Count_hist
```


```{r}
summary(Vgsales_df$User_Count)
```

```{r}
Rating_bar = ggplot(Vgsales_df, aes(x=Rating, fill=Rating)) + geom_bar()
Rating_bar
```

## Multivariate plots
```{r}
fig(20,8)
sales_by_platform <- ggplot(Vgsales_df, aes(Platform, Global_Sales, fill = Platform)) + geom_bar(stat="identity") + theme(axis.text.x=element_text(angle=90, vjust = .5, hjust = 1)) + labs(x="Platform", y="Global_Series", title="Sales by Platform")
sales_by_platform
```

```{r}
Vgsales_df %>% select(Publisher, Global_Sales) %>% group_by(Publisher) %>% summarise(Total_sales=sum(Global_Sales)) %>% arrange(desc(Total_sales)) %>%  head(10) %>% ggplot(aes(x=Publisher, y=Total_sales, fill=Publisher)) + geom_bar(stat="identity") + theme(axis.text.x=element_text(angle = 90, hjust = 1, vjust = .5, size=10)) + labs(x="Developer", y="Global Sales", title="Top 10 selling Developers")
```

```{r}
summary(Vgsales_df)
str(Vgsales_df)

Vgsales_df %>% select(Name, Global_Sales) %>% arrange(desc(Global_Sales)) %>% head(10) %>% ggplot(aes(x=Name, y = Global_Sales, fill = Name)) + geom_bar(stat="identity") + theme(axis.text.x=element_text(angle = 90,vjust = .5, hjust = 1)) + labs(x="Game", y="Global sales", title = "Top 10 best selling games")
```

```{r}
ggplot(Vgsales_df, aes(Game_Age, Global_Sales)) + geom_jitter(color="darkviolet")
```

```{r}
ggplot(Vgsales_df, aes(Critic_Score, Global_Sales)) + geom_jitter(color="darkblue")
```

```{r}
ggplot(Vgsales_df, aes(Critic_Count, Global_Sales)) + geom_jitter(color="red")
```

```{r}
ggplot(Vgsales_df, aes(User_Count, Global_Sales)) + geom_jitter(color="orange")
```

# Statistical models for regression

## KNN Regressor

### Data preparation

```{r}
summary(Vgsales_df)
Vgsales_df <- Vgsales_df[,-1]
knn.df <- Vgsales_df
head(knn.df)
```



```{r}
str(knn.df)
summary(knn.df)
for (i in 1:dim(knn.df)[2]) {
  knn.df[,i] <- as.numeric(knn.df[,i])
}
head(knn.df)
```


```{r}
knn.df1 <- sapply(knn.df[,1:(dim(knn.df)[2]-1)], scale)
knn.df1 <- as.data.frame(knn.df1)
knn.df <- cbind(knn.df1, knn.df$Global_Sales)
names(knn.df)[11] = "Global_Sales"
head(knn.df)
```

# Train and test

```{r}
set.seed(5)

train.size <- floor(.7*nrow(knn.df))
train.index <- sample(1:nrow(knn.df), train.size, replace=F)
train.set <- knn.df[train.index,]
test.set <- knn.df[-train.index,]
train.x <- train.set[,-11] # exclude the global sales column
train.y <- train.set[,11] # Only the global sales column
test.x <- test.set[,-11] # exclude the global sales column
test.y <- test.set[,11]  # Only the global sales column
```


```{r}
pred_003 <- FNN::knn.reg(train = train.x, test = test.x, y = train.y, k = 3)
diff3 = test.y-pred_003$pred
test_mse = mean(diff3^2)
test_mse
```



























